name: to_string_pretty
description: Prints an object pretty.
version: 1.1.1
repository: https://github.com/pubmskim/to_string_pretty
environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.14.4